language: python
python:
  - "3.6"
env:
  - DJANGO="Django>=2.0,<2.1"
matrix:
  include:
  - env: DJANGO="Django>=2.0,<2.1"
  - env: DJANGO="Django>=1.11,<1.12"
  - env: DJANGO="Django>=1.10,<1.11"
  - env: DJANGO="Django>=1.9,<1.10"
  - env: DJANGO="Django>=1.8,<1.9"
  - python: "3.5"
  - python: "3.4"
  - python: "2.7"
    env: DJANGO="Django>=1.11,<1.12"
install:
  - pip install --upgrade -q pip setuptools
  - pip install -q $DJANGO
  - pip install -e .
script:
  - ./runtests.py
